### ISSUE TITLE
Log in as buyer

### ISSUE THREAD

**Issue by alagappan2578** [fssa-batch3/sesslyn.johnson__web_project#23]
### Description of issue

While log in as buyer in log in page if we enter wrong name it accept.

without enter name we can log in So, no need that feild 

```
Path:      /pages/homepage.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--casas-minimal.netlify.app%2Fpages%2Fhomepage.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #3](https://deploy-preview-3--casas-minimal.netlify.app/pages/homepage.html)

**Comment by Sesslyn041215** [comment]
Issue Solved

**Comment by alagappan2578** [comment]
Verified ok
