### ISSUE TITLE
Buyer profile edit page

### ISSUE THREAD

**Issue by alagappan2578** [fssa-batch3/sesslyn.johnson__web_project#24]
### Description of issue

same issue What I mentioned for seller edit page.

```
Path:      /pages/profile/edit_profile.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--casas-minimal.netlify.app%2Fpages%2Fprofile%2Fedit_profile.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #3](https://deploy-preview-3--casas-minimal.netlify.app/pages/profile/edit_profile.html)

**Comment by Sesslyn041215** [comment]
Issue Solved

**Comment by alagappan2578** [comment]
verified ok
