### ISSUE TITLE
In register page in email I give a space it take a space.

### ISSUE THREAD

**Issue by deemoseenu** [fssa-batch3/sesslyn.johnson__web_project#26]
### Description issue
In register page In email I give space It take a space and register it. 

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /pages/profile/login.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--casas-minimal.netlify.app%2Fpages%2Fprofile%2Flogin.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #3](https://deploy-preview-3--casas-minimal.netlify.app/pages/profile/login.html)

**Comment by Sesslyn041215** [comment]
Issue Solved

**Comment by deemoseenu** [comment]
solved
