### ISSUE TITLE
sign up and login issue 

### ISSUE THREAD

**Issue by alagappan2578** [fssa-batch3/sesslyn.johnson__web_project#9]
### Description of issue

In email input first character " " (space) got accepted.

```
Path:      /pages/seller/seller_register.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--casas-minimal.netlify.app%2Fpages%2Fseller%2Fseller_register.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #3](https://deploy-preview-3--casas-minimal.netlify.app/pages/seller/seller_register.html)

**Comment by Sesslyn041215** [comment]
Issue Solved

**Comment by alagappan2578** [comment]
Not needed
